// Obtain the img element, and assign it to the image variable
let content = document.querySelector('.js-generated.content')

let dogContent = document.createElement('div')
dogContent.setAttribute('class', 'dog-content')
content.append(dogContent)

let dogImage = document.createElement('img')
dogImage.setAttribute('dog-image')
dogImage.setAttribute('src', './NYU-Into-Assesment-/Coco.jpg')
dogContent.append(Image)

// Obtain the 'shrink-grow' button, and assign it to the changeSize variable
let changeSize = document.createElement('img');
changeSize.textContent = 'Shrink/Grow'
changeSize.style.fontSize = '35px'
dogImage.append(changeSize);
<div class="column">
        <h1>Generated by JavaScript</h1>
        <h3>Output:</h3>
        <div class="js-generated content"></div>

//DO NOT CHANGE THE FOLLOWING CODE
changeSize.addEventListener("click", function() {
  if (image.style.height == "100px") {
    image.style.height = "25px"
  }
  else {
    image.style.height = "100px"
  }
})